name: Build

on: 
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  formatting-check:
    name: Build Check
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: autogen
      run: sh ./autogen.sh

    - name: configure
      run: ./configure

    - name: make
      run: make -j
