name: CMake

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  BUILD_TYPE: RelWithDebInfo

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: "Create build directory and run CMake"
        run: cmake -S . -B build -G "Cmake" -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}
      - name: "Build Project" 
        run: cmake --build build --target all --config Release -- -j4
